version: "3.8"
services:
  hedge-v3-server:
    container_name: hedge-v3-server
    image: hedge-v3-server:dev
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - STORAGE_DIR=/data
      - TOKEN=dev
    ports:
      - "19000:19000"
    volumes:
      - /path/to/server:/server
      - /path/to/data:/data
